In [2]:
#Project Description
#This project processes weekly forecast sales data and combine new week's data 
#Combined data is visualized using Tableau 

import pandas as pd

#importing the master file 

AllWeek= pd.read_csv('AllWeek.csv')

In [5]:
week_11 = pd.read_csv('Week_11.csv')
week_12 = pd.read_csv('Week_12.csv')
week_13 = pd.read_csv('Week_13.csv')
week_14 = pd.read_csv('Week_14.csv')

In [8]:
#replacing NA to blank

week_11 = week_11.fillna('')
week_12 = week_12.fillna('')
week_13 = week_13.fillna('')
week_14 = week_14.fillna('')

#replacing blanks in columns to _

week_11.columns = week_11.columns.str.replace(" ","_")
week_12.columns = week_12.columns.str.replace(" ","_")
week_13.columns = week_13.columns.str.replace(" ","_")
week_14.columns = week_14.columns.str.replace(" ","_")

#Adding columns to indicate the capturing date

week_11['SnapDate']="2022/03/14"
week_12['SnapDate']="2022/03/21"
week_13['SnapDate']="2022/03/28"
week_14['SnapDate']="2022/04/04"

In [9]:
#Re-defining data frames to drop columns

week_11 = week_11[['Opportunity_ID', 'Opportunity', 'Account', 'Territory',
       'Territory_(Parent_Territory)', 'Country/Region',
       'Primary_Business_Line', 'Quarter/Calendar_Year',
       'Employee_Responsible', 'Close_Date', 'Product_Category',
       'Product_Category_ID', 'Lifecycle_Status', 'Distribution_Channel',
       'Probability_%', 'Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023','SnapDate']]

week_12 = week_12[['Opportunity_ID', 'Opportunity', 'Account', 'Territory',
       'Territory_(Parent_Territory)', 'Country/Region',
       'Primary_Business_Line', 'Quarter/Calendar_Year',
       'Employee_Responsible', 'Close_Date', 'Product_Category',
       'Product_Category_ID', 'Lifecycle_Status', 'Distribution_Channel',
       'Probability_%', 'Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023','SnapDate']]

week_13 = week_13[['Opportunity_ID', 'Opportunity', 'Account', 'Territory',
       'Territory_(Parent_Territory)', 'Country/Region',
       'Primary_Business_Line', 'Quarter/Calendar_Year',
       'Employee_Responsible', 'Close_Date', 'Product_Category',
       'Product_Category_ID', 'Lifecycle_Status', 'Distribution_Channel',
       'Probability_%', 'Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023','SnapDate']]

week_14 = week_14[['Opportunity_ID', 'Opportunity', 'Account', 'Territory',
       'Territory_(Parent_Territory)', 'Country/Region',
       'Primary_Business_Line', 'Quarter/Calendar_Year',
       'Employee_Responsible', 'Close_Date', 'Product_Category',
       'Product_Category_ID', 'Lifecycle_Status', 'Distribution_Channel',
       'Probability_%', 'Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023','SnapDate']]

In [10]:
#changing value based columns to numeric 

AllWeek[['Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023']] =  AllWeek[['Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023']].apply(pd.to_numeric)

week_11[['Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023']] =  week_11[['Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023']].apply(pd.to_numeric)
week_12[['Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023']] =  week_12[['Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023']].apply(pd.to_numeric)
                                                   
week_13[['Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023']] =  week_13[['Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023']].apply(pd.to_numeric)

week_14[['Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023']] =  week_14[['Negotiated_value', 'OB_-_Q1_2022', 'NS_-_Q1_2022',
       'OB_-_Q2_2022', 'NS_-_Q2_2022', 'OB_-_Q3_2022', 'NS_-_Q4_2022',
       'OB_-_Q4_2022', 'NS_-_Q3_2022', 'NS_-_Q1_2023', 'NS_-_Q2_2023',
       'NS_-_Q3_2023', 'NS_-_Q4_2023', 'OB_-_Q1_2023', 'OB_-_Q2_2023',
       'OB_-_Q3_2023', 'OB_-_Q4_2023']].apply(pd.to_numeric)

In [11]:
#appending each week's csv file to the master file

week_11.to_csv('AllWeek.csv',mode='a',index=False,header=False)
week_12.to_csv('AllWeek.csv',mode='a',index=False,header=False)
week_13.to_csv('AllWeek.csv',mode='a',index=False,header=False)
week_14.to_csv('AllWeek.csv',mode='a',index=False,header=False)